### ISSUE TITLE
Review Diana's Work on Prototype App

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-knack-development-review#1]

**Comment by TracyLinder** [comment]
@dianamartin Can you update this to document the work you've done to date? Thx.

**Comment by dianamartin** [comment]
moved this to: https://github.com/cityofaustin/atd-knack-development-review/issues/1

**Comment by dianamartin** [comment]
### Sangeeta's reponses
- Which Vision Team Members are Selected Per Review? Do we have a concrete list of individuals?
>Yes, we do have a list of individuals.  PM will select the members to review depending on the type of case and other review criteria. 

- Does a review go on hold? 
>Yes, it may for some projects that are long term.
- [x] Added `On Hold` as a status for the development review case

- What happens when a group denies? Is there any negotiation with PM? Does the reviewer ever change their mind? 
>Yes, there is negotiation with PM based on reviews by other Vision Team members, or other circumstances. Yes, the reviewer may change their mind.

- Do we need to show the Review Process Status from AMANDA?

- What if the reviewer is out of the office / no longer on the team? 
>Yes, as PM we do need the ability to reassign.  The Vision team member should be able to assign the review to another team member in their work group if they are going to be on vacation. 
- [x] Added the `Reassign` function on the **My Reviews** table

   - We want the ability to re-assign the review, correct?  
>Yes

- Are we going to require any kind of signature? 
>Not really signature, but something that says they have submitted/ completed their review.

- Is there a field in AMANDA that would indicate if a Site Plan needs a transportation review?
> Yes, its called “ATD Engineering Review”

- What will user permissions look like?
   - Right now I have admin, project manager and viewer/reviewer.  
>I think that sounds about right for now

**Comment by dianamartin** [comment]
## To Do
- [x] Edit Cycle form - Cycle No (make not editable)
- [x] Create task for due date NO RESPONSE RECEIVED
Called it `Past Due - NO RESPONSE RECEIVED`
ACTION:
- When `Reviewer Comment` is blank
- AUTO NO RESPONSE DATE is before today
SET
- NO RESPONSE RECEIVED - custom value- 1

## Follow-up
- TDSD, what info from AMANDA if we were able to import info
- Does the PM want notifications when Reviewer reassigns
- What is the Vision Team list look like, please send

**Comment by dianamartin** [comment]
## New Feature/Enhancement
- [x] PM needs to see the unified responses provided to customer (pasted in AMANDA)
  - [ ] Needs it's own table, viewing on the project page
>We decided to add the `Unified Comment` directly on the Review Cycle table. 
- [x] Removed `Requester` field
- [x] Create new Advanced Search page, to be able to search by the case (Dev Review table)

### Update `Development Review` Object Table
- [x] (Attachment URL) - Users want to see the link to the attachment URL (add a field)
- [x] Special Notes Field: Make it so users can format the text (bold/italic/bullets)
>See DTS Portal, `Change Log` page. Had to change to `Rich Text` field.
- [x] New Field: `TIA` , Type: Boolean (Y/N) , Values: 'Yes', 'No'
- [x] New Field: `Off-Site Mitigation`, same as TIA field
  - Put these 2 fields right underneath the Site Plan # field
- [x] New Field: `Area`, Values: North, Central, South

### Update `Review Cycle` Object Table
- [ ] Field: Review Request Status….Change name to AMANDA Review Status, Update the values to match the AMANDA process values
- [x] Field: Final Response: Change Name to 'Cycle Status'

### Edit **Cycle Form**
- [x] Add `Attachment` to reviewer comments table

### Update `Review Comments` Object Table
- [x] Reviewer Comments Status: Change the values `Recommended`, `Not Recommended`, `Recommended With Conditions` 

### Email Configuration
- [x] Review Comment Reassign Email: Amend 1st sentence to remove the word `comment`
- [ ] Need to recreate form `Reassign Reviewer` form
>Thought I needed to, Knack was being weird and not showing that I could change the email field to the assigner person. 
- [x] Create new auto email so the PM is notified when a review is reassigned. (Same as the Review Comment Reassign Email)


### Advanced Search - Review Comments
- [x] Add address & vision team group search options

### Bug Fixes/More Testing
- [x] Diana added 3 vision members, but only 2 showed up in the Reviewer Comments table (_Cambria Hotels & Suites Project_)
- [x] Issue: When PM added Urban Trails review on cycle #2, 2 Urban Trail reviews were inserted

### Use Case: 
Vision reviewer denies the review. The PM decides to move forward w/ an overall approval anyway. We need to know (for record keeping purposes) that the vision reviewer denied, and the PM override that denial. `Recommended With Conditions` 

- [ ] User Documentation - So customer can perform UAT

**Comment by dianamartin** [comment]
@TracyLinder I estimate this to be hours

**Comment by amenity** [comment]
Remainder of this work is captured in https://github.com/cityofaustin/atd-data-tech/issues/605.
