### ISSUE TITLE
A feature that helps the PM consolidate all reviews into 1 unified review comment. 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-development-review#10]

**Comment by dianamartin** [comment]
Added field `Final Response` (Y/N) and another field `Unified Comment`. Added on Review Cycle table and edit form. Allows the PM to determine if they've written a final response and a field to aggregate the reviewer comments. 

Added a table of the reviewer comments associated to the review cycle.

**Comment by amenity** [comment]
@dianamartin  - does this need more review? If so, what/who?

**Comment by dianamartin** [comment]
Functionality is in place, users had no comments on this.
