### ISSUE TITLE
Ability for the PM to quickly see a workload overview, with emphasis on upcoming deadlines

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-development-review#11]

**Comment by dianamartin** [comment]
On the main "Development Review" table there is a column from the related review cycles that notate the Due Dates of the review cycles. (They can't be sorted because they're coming from the related object table)

**Comment by amenity** [comment]
@dianamartin  - does this need more review? If so, what/who?

**Comment by dianamartin** [comment]
@amenity UAT was completed on Friday. @TracyLinder can you tell me whether this was accepted?

**Comment by dianamartin** [comment]
Functionality is in place, users had no comments on this.
