### ISSUE TITLE
Ability to query a user and see their reviews, including the status and outcome. 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-development-review#12]

**Comment by dianamartin** [comment]
In the `Advanced Search` page, you can query by `Assigned Reviewer` and the results list allows you to see `Final Outcome` and `Comment Status`.

**Comment by amenity** [comment]
@dianamartin  - does this need more review? If so, what/who?

**Comment by dianamartin** [comment]
@amenity UAT was completed on Friday. @TracyLinder can you tell me whether this was accepted?

**Comment by dianamartin** [comment]
Functionality is in place, users had no comments on this.
