### ISSUE TITLE
Ability to query a case by a reviewer name or Site Plan case number

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-development-review#14]

**Comment by dianamartin** [comment]
Created **Advanced Search** page, fields that can be queried

- Keyword Search
- Development Review  
- Cycle #
- Folder RSN #
- Site Plan # _**(addresses searching for site plans)**_
- Review Status
- Reviewer Comment
- Requested By
- Assigned Reviewer _**(addresses searching by reviewer name)**_
- Due Date
- Completed Date

**Comment by amenity** [comment]
@dianamartin  - does this need more review? If so, what/who?

**Comment by dianamartin** [comment]
@amenity UAT was completed on Friday. @TracyLinder can you tell me whether this was accepted?

**Comment by dianamartin** [comment]
Functionality is in place, users had no comments on this.
