### ISSUE TITLE
Import Data: Due 9/30/19

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-knack-development-review#20]
Import development review case details for cases with an open TDSD review in AMANDA. 
- The query used is [here](https://github.com/cityofaustin/atd-amanda/blob/master/plsql-queries/TDSD_Reviews.sql).

**Comment by TracyLinder** [comment]
[TDSD Import Data.xlsx](https://github.com/cityofaustin/atd-knack-development-review/files/3661052/TDSD.Import.Data.xlsx)

* Sheet 1 (Case Details) - Includes all Development Review table details available in AMANDA, other than the attachment URL. 
    * TIA, Mitigation, Area fields are not available
* Sheet 2 (Attachment URL) - Includes the attachment comment where available, mapped by ROW ID.

**Comment by dianamartin** [comment]
- Downloaded the spreadsheets and save them to [network folder](G:\ATD\ATD_GIS\02_ENT_APPLICATIONS\app_TDSD_Unified_Comment_Tracker\import_tables) for import.
- Converted cases to .csv
- Saved as to capture the attachments tab 
- [x] Import `Development Cases` into Knack
- [x] Import `Attachment links` from Amanda
