### ISSUE TITLE
Bug: Instructions/Notes Field Not Visible

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-knack-development-review#21]
The instructions field is not visible on the View Development Review Details Page.
See [this](https://atd.knack.com/development-services#development-reviews/view-development-review-details/5d8d90229504760010f4b831/) example.

**Comment by dianamartin** [comment]
@TracyLinder I fixed this issue. 
![image](https://user-images.githubusercontent.com/21112975/65907754-92d5fc00-e38a-11e9-8537-1bb92f6551f4.png)
